<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="username">User_Name</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <label for="password">Re-enter Password</label>
        <?php echo $this->tag->textField("password2"); ?>
    </p>

    <p>
        <label for="Role">Role</label>
        <?php echo $this->tag->textField("role"); ?>
    </p>


    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>
        <?php
    echo $this->tag->linkTo(
        'login',
        'login Here !'
    );?>


</form>